# Config for training ALAE on CelebA-HQ at resolution 256x256

NAME: mammogans_512
DATASET:
  PART_COUNT: 16
  SIZE: 16480
  SIZE_TEST: 16484 - 16480
  PATH: /home/vikki/Desktop/BTP/MammoGan/data/datasets/mammogans_512/tfrecords/mammogans_512-r%02d.tfrecords.%03d
  PATH_TEST: /home/vikki/Desktop/BTP/MammoGan/data/datasets/mammogans_512-test/tfrecords/mammogans_512-r%02d.tfrecords.%03d
  MAX_RESOLUTION_LEVEL: 9
  SAMPLES_PATH: /home/vikki/Desktop/BTP/Bi-Pro-GAN/aiims_cc_512
  STYLE_MIX_PATH: style_mixing/test_images/set_ffhq
MODEL:
  LATENT_SPACE_SIZE: 512
  LAYER_COUNT: 8
  MAX_CHANNEL_COUNT: 512
  START_CHANNEL_COUNT: 64
  DLATENT_AVG_BETA: 0.995
  MAPPING_LAYERS: 8
OUTPUT_DIR: mammogans_512_result
TRAIN:
  BASE_LEARNING_RATE: 0.002
  EPOCHS_PER_LOD: 25
  LEARNING_DECAY_RATE: 0.1
  LEARNING_DECAY_STEPS: []
  TRAIN_EPOCHS: 185
  #                    4       8       16       32       64       128        256       512       1024
  LOD_2_BATCH_8GPU: [512,    256,     128,      64,      32,       32,        32,       32,        32]
  LOD_2_BATCH_4GPU: [512,    256,     128,      64,      32,       32,        32,       32,        16]
  LOD_2_BATCH_2GPU: [128,    128,     128,      64,      32,       32,        16]
  LOD_2_BATCH_1GPU: [128,    128,     128,      64,      32,       16]


  LEARNING_RATES: [0.0015,  0.0015,   0.0015,   0.0015,  0.0015,   0.0015,     0.0015,     0.003,    0.003]
